apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: flux-system
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`grafana.svc.local`)
      services:
        - kind: Service
          name: kube-prometheus-stack-grafana 
          port: 80 
