---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/part-of: metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  dependsOn:
    - name: metallb-crds
  interval: 1h
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: "0.14"
      sourceRef:
        kind: GitRepository
        name: metallb
  values:
    crds:
      enabled: true
    prometheus:
      metricsBackend: prometheus
      prometheusCR:
        enabled: true
