apiVersion: v1
kind: Service
metadata:
  name: myspeed 
  namespace: myspeed 
labels:
    app: myspeed 
spec:
  type: ClusterIP
  ports:
    - port: 5216 
      name: http
      protocol: TCP
  selector:
    app: myspeed 
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myspeed-ingress
  namespace: myspeed 
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`speed.svc.local`)
      services:
        - kind: Service
          name: myspeed
          port: 5216
