apiVersion: v1
kind: Service
metadata:
  name: myspeed 
  namespace: myspeed 
labels:
    app: myspeed 
spec:
  type: ClusterIP
  ports:
    - port: 5216 
      name: http
      protocol: TCP
  selector:
    app: myspeed 
